// tb_matmul_sw.sv — benchmarks software 4x4 matrix multiply on the RV32IM CPU
//
// Measures cycles from the start of the compute loop to the last store.
// Prints the cycle count and speedup vs the 6-cycle hardware accelerator.
//
// Requires program.hex to be generated by mat-accel/tb/assemble.py

`timescale 1ns/1ps

module tb_matmul_sw;

reg clk;
reg rst;

wire [31:0] result;

top dut (
    .clk(clk),
    .rst(rst),
    .result(result)
);

initial clk = 0;
always #5 clk = ~clk;

integer cyc;
integer t_start;
integer t_end;

initial begin
    cyc     = 0;
    t_start = 0;
    t_end   = 0;
end

// cycle counter
always @(posedge clk) begin
    #1;
    cyc = cyc + 1;
end

// detect start of timed section: PC hits 0x0D0 (first instruction of compute loop)
always @(posedge clk) begin
    if (dut.pc_out == 32'h0D0 && t_start == 0) begin
        #1;
        t_start = cyc;
        $display("timed section started at cycle %0d  (PC=0x0D0)", t_start);
    end
end

// detect end: C[3][3] written to data_mem word 47 (byte addr 0x0BC)
// C[3][3] = 16 when A=identity, B=[1..16]
always @(posedge clk) begin
    if (dut.u_dmem.memory[47] === 32'd16 && t_end == 0 && t_start !== 0) begin
        #1;
        t_end = cyc;
        $display("last store (C[15]=16) at cycle %0d", t_end);
        $display("------------------------------------------");
        $display("software cycles : %0d", t_end - t_start);
        $display("hardware cycles : 6");
        $display("speedup         : ~%0dx", (t_end - t_start) / 6);
        $display("------------------------------------------");
        $finish;
    end
end

// safety timeout
initial begin
    repeat(3000) @(posedge clk);
    $display("TIMEOUT — computation did not finish in 3000 cycles");
    $finish;
end

initial begin
    rst = 1;
    repeat(2) @(posedge clk);
    #1 rst = 0;
end

endmodule
